name: Create new Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"          
                    
      - name: Build and pack assemblies
        run: dotnet pack ./srcs --configuration Release /p:BuildVersion=${{ github.run_number }} --output ./srcs/bin/Publish
          
      - name: Store artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: artifacts
          path: ./srcs/bin/Publish 
        
      - name: Publish artifact to nuget
        run: dotnet nuget push ./srcs/bin/Publish/*.nupkg --api-key ${{ secrets.NUGET_TOKEN_FOR_GITHUB }} --skip-duplicate --no-symbols true
